version: '3.7'

services:
  database:
    image: postgres
    container_name: rentx-database
    # restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_USER=postgres
      - POSTGRES_DB=rentx
    volumes:
      - pgdata:/data/postgres
  api:
    build: .
    container_name: rentx-api
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database

volumes:
  pgdata:
    driver: local
