version: '3.7'

services:
  api:
    container_name: rentx-api
    command: yarn dev:server
    build: .
    ports:
      - 3333:3333
    environment:
      - DB_HOST=rentx-database
    volumes:
      - .:/usr/app
    networks:
      - rentx-network
    depends_on:
      - database
      - redis

  database:
    container_name: rentx-database
    image: postgres:14.1-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - rentx-volume:/data/postgres
    networks:
      - rentx-network

  redis:
    container_name: rentx-redis
    image: redis:6.2-alpine
    ports:
      - 6379:6379
    volumes:
      - rentx-volume:/data/redis
    networks:
      - rentx-network

volumes:
  rentx-volume:
    driver: local

networks:
  rentx-network:
    driver: bridge
